### ISSUE TITLE
cannt batch translate english to persian

### ISSUE THREAD

**Issue by dumbdreamed** [kelciour/google-translate#1] opened 2021-02-14 05:58 UTC
hi, really thanks for your hard work on this beautiful add on, I'm trying to translate more than one card at the same time with identical note type but I keep getting this error.it seems that this error only happens when I  want to translate English to Persian. in translating English to other languages I  don't have any problem.in other words, I can translate English to Persian only a word at a time not batch translation.

Error:

Traceback (most recent call last):
  File "C:\Users\dreameddumb\AppData\Roaming\Anki2\addons21\1536291224\__init__.py", line 205, in accept
    assert len(nids) == len(translated), "Translated: {} notes != {}\n\n-------------\n{}\n-------------\n".format(len(nids), len(translated), urllib.parse.unquote(query))
AssertionError: Translated: 3 notes != 1

-------------
Staple
~~~
Sprawl
~~~
Tempest
-------------

**Comment by kelciour** [comment] 2021-02-14 11:40
> to Persian

Thank you. It was an important piece of information. The add-on should be fixed now. If you won't receive a notification from Anki, go to Tools - Add-ons and Check for Updates.

**Closed as completed by kelciour** 2021-02-14 11:40 UTC

**Comment by dumbdreamed** [comment] 2021-02-14 18:28
really appreciate it, my friend, it worked for a couple of tries but after that, I keep getting this weird error in the destination field,
for example, I tried to translate this word from English to Persian.
front of the card=======>constituent
back of the card========>constituenthjp_bilink_data = [{"card_id": "1613283752503" ، "desc": "اساسی" ، "dir": "→"} ، {"card_id": "1613283768585"، "desc": "قانون اساسی"، "dir": "→"} ، {"card_id": "1613283785569" ، "desc": "قانون اساسی" ، "dir": "→"} ، {"card_id": "1613283796101" ، "desc": "تشکیل می دهد" ، "dir" ":" "}]

![2021-02-14_21-57-07](https://user-images.githubusercontent.com/64626106/107885453-a64a1e80-6f0f-11eb-90c8-f964cf34f9d9.png)

**Comment by kelciour** [comment] 2021-02-14 19:22
It looks like it was caused by a different add-on. Maybe this one - https://ankiweb.net/shared/info/1420819673

I'm not familiar with it and don't know how it works. Maybe the front field contains some hidden html (Select a field and press Ctrl+Shift+X) that was translated by Google. Maybe try to use Google Translate with Format set to text.

If  you could export this card and send it to me, maybe I'd have some idea what to do.

**Comment by dumbdreamed** [comment] 2021-02-15 05:12
you are amazing my friend, this error was because of the exact add on that you mentioned which I use to link cards together. really really thanks for what you've done.it saves a lot of time and effort.
